# OSI ONE AGENT - Application Configuration

app:
  name: "OSI ONE AGENT"
  version: "1.0.0"
  log_level: "INFO"
  debug: false
  openai:
    api_key: ""  # Will be read from environment variable OPENAI_API_KEY
  azure_devops:
    organization: "BarrettBusinessServicesIncorporated"
    project: "Transform"

nlp:
  provider: "openai"
  model: "gpt-4"
  max_tokens: 1000
  temperature: 0.1
  timeout: 30

ui:
  theme: "dark"
  show_progress: true
  auto_complete: true
  max_history: 100

performance:
  cache_ttl: 300  # 5 minutes
  max_retries: 3
  timeout: 30
  rate_limit_delay: 1.0

security:
  token_encryption: true
  token_rotation: true
  audit_logging: true 